name: Build Feeds

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:

concurrency:
  group: feeds-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Sync with remote
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config pull.rebase true
          git config rebase.autoStash true
          git fetch origin main
          git pull --rebase origin main

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pyyaml

      - name: Build JSON
        run: |
          python scripts/fetch_feeds.py

      - name: Commit feeds.json if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update feeds.json"
          file_pattern: data/feeds.json
