name: Build Feeds

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing with GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pyyaml

      - name: Build JSON
        run: |
          python scripts/fetch_feeds.py

      # ⬇️ This replaces your "Commit artifacts" block
      - name: Commit feeds.json if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update feeds.json"
          file_pattern: data/feeds.json
