name: Build Feeds

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pyyaml

      - name: Build JSON
        run: |
          python scripts/fetch_feeds.py

      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/feeds.json
          if ! git diff --staged --quiet; then
            git commit -m "chore: update feeds.json"
            git push
          else
            echo "No changes to commit."
